#ifndef VANADIUM_VERSION_FILE_H
#define VANADIUM_VERSION_FILE_H

#define VANADIUM_VERSION_MAJOR 0
#define VANADIUM_VERSION_MINOR 2
#define VANADIUM_VERSION_PATCH 5
#define VANADIUM_VERSION "0.2.5"

#endif  // VANADIUM_VERSION_FILE_H
