#include "KeyboardKeyCode.h"

#include "Assert.h"
#include "StringHash.h"

namespace vanadium::keyboard {

std::string toString(KeyCode arg) {
  switch (arg) {
    case KeyCode::Unknown:
      return "Unknown";
    case KeyCode::A:
      return "A";
    case KeyCode::B:
      return "B";
    case KeyCode::C:
      return "C";
    case KeyCode::D:
      return "D";
    case KeyCode::E:
      return "E";
    case KeyCode::F:
      return "F";
    case KeyCode::G:
      return "G";
    case KeyCode::H:
      return "H";
    case KeyCode::I:
      return "I";
    case KeyCode::J:
      return "J";
    case KeyCode::K:
      return "K";
    case KeyCode::L:
      return "L";
    case KeyCode::M:
      return "M";
    case KeyCode::N:
      return "N";
    case KeyCode::O:
      return "O";
    case KeyCode::P:
      return "P";
    case KeyCode::Q:
      return "Q";
    case KeyCode::R:
      return "R";
    case KeyCode::S:
      return "S";
    case KeyCode::T:
      return "T";
    case KeyCode::U:
      return "U";
    case KeyCode::V:
      return "V";
    case KeyCode::W:
      return "W";
    case KeyCode::X:
      return "X";
    case KeyCode::Y:
      return "Y";
    case KeyCode::Z:
      return "Z";
    case KeyCode::Num_1:
      return "Num_1";
    case KeyCode::Num_2:
      return "Num_2";
    case KeyCode::Num_3:
      return "Num_3";
    case KeyCode::Num_4:
      return "Num_4";
    case KeyCode::Num_5:
      return "Num_5";
    case KeyCode::Num_6:
      return "Num_6";
    case KeyCode::Num_7:
      return "Num_7";
    case KeyCode::Num_8:
      return "Num_8";
    case KeyCode::Num_9:
      return "Num_9";
    case KeyCode::Num_10:
      return "Num_10";
    case KeyCode::Return:
      return "Return";
    case KeyCode::Escape:
      return "Escape";
    case KeyCode::Backspace:
      return "Backspace";
    case KeyCode::Tab:
      return "Tab";
    case KeyCode::Space:
      return "Space";
    case KeyCode::Minus:
      return "Minus";
    case KeyCode::Equals:
      return "Equals";
    case KeyCode::LeftBracket:
      return "LeftBracket";
    case KeyCode::RightBracket:
      return "RightBracket";
    case KeyCode::Backslash:
      return "Backslash";
    case KeyCode::Semicolon:
      return "Semicolon";
    case KeyCode::Apostrophe:
      return "Apostrophe";
    case KeyCode::Grave:
      return "Grave";
    case KeyCode::Comma:
      return "Comma";
    case KeyCode::Period:
      return "Period";
    case KeyCode::Slash:
      return "Slash";
    case KeyCode::Capslock:
      return "Capslock";
    case KeyCode::F1:
      return "F1";
    case KeyCode::F2:
      return "F2";
    case KeyCode::F3:
      return "F3";
    case KeyCode::F4:
      return "F4";
    case KeyCode::F5:
      return "F5";
    case KeyCode::F6:
      return "F6";
    case KeyCode::F7:
      return "F7";
    case KeyCode::F8:
      return "F8";
    case KeyCode::F9:
      return "F9";
    case KeyCode::F10:
      return "F10";
    case KeyCode::F11:
      return "F11";
    case KeyCode::F12:
      return "F12";
    case KeyCode::PrintScreen:
      return "PrintScreen";
    case KeyCode::ScrollLock:
      return "ScrollLock";
    case KeyCode::Pause:
      return "Pause";
    case KeyCode::Insert:
      return "Insert";
    case KeyCode::Home:
      return "Home";
    case KeyCode::PageUp:
      return "PageUp";
    case KeyCode::Delete:
      return "Delete";
    case KeyCode::End:
      return "End";
    case KeyCode::PageDown:
      return "PageDown";
    case KeyCode::Right:
      return "Right";
    case KeyCode::Left:
      return "Left";
    case KeyCode::Down:
      return "Down";
    case KeyCode::Up:
      return "Up";
    case KeyCode::NumLock:
      return "NumLock";
    case KeyCode::KPDivide:
      return "KPDivide";
    case KeyCode::KPMultiply:
      return "KPMultiply";
    case KeyCode::KP_Minus:
      return "KP_Minus";
    case KeyCode::KP_Plus:
      return "KP_Plus";
    case KeyCode::KP_Enter:
      return "KP_Enter";
    case KeyCode::KP_1:
      return "KP_1";
    case KeyCode::KP_2:
      return "KP_2";
    case KeyCode::KP_3:
      return "KP_3";
    case KeyCode::KP_4:
      return "KP_4";
    case KeyCode::KP_5:
      return "KP_5";
    case KeyCode::KP_6:
      return "KP_6";
    case KeyCode::KP_7:
      return "KP_7";
    case KeyCode::KP_8:
      return "KP_8";
    case KeyCode::KP_9:
      return "KP_9";
    case KeyCode::KP_0:
      return "KP_0";
    case KeyCode::KP_Period:
      return "KP_Period";
    case KeyCode::KP_Equals:
      return "KP_Equals";
    case KeyCode::F13:
      return "F13";
    case KeyCode::F14:
      return "F14";
    case KeyCode::F15:
      return "F15";
    case KeyCode::F16:
      return "F16";
    case KeyCode::F17:
      return "F17";
    case KeyCode::F18:
      return "F18";
    case KeyCode::F19:
      return "F19";
    case KeyCode::F20:
      return "F20";
    case KeyCode::F21:
      return "F21";
    case KeyCode::F22:
      return "F22";
    case KeyCode::F23:
      return "F23";
    case KeyCode::F24:
      return "F24";
    case KeyCode::Execute:
      return "Execute";
    case KeyCode::Help:
      return "Help";
    case KeyCode::Menu:
      return "Menu";
    case KeyCode::Select:
      return "Select";
    case KeyCode::Stop:
      return "Stop";
    case KeyCode::Redo:
      return "Redo";
    case KeyCode::Undo:
      return "Undo";
    case KeyCode::Cut:
      return "Cut";
    case KeyCode::Copy:
      return "Copy";
    case KeyCode::Paste:
      return "Paste";
    case KeyCode::Find:
      return "Find";
    case KeyCode::Mute:
      return "Mute";
    case KeyCode::VolumeUp:
      return "VolumeUp";
    case KeyCode::VolumeDown:
      return "VolumeDown";
    case KeyCode::KP_Comma:
      return "KP_Comma";
    case KeyCode::LCtrl:
      return "LCtrl";
    case KeyCode::LShift:
      return "LShift";
    case KeyCode::LAlt:
      return "LAlt";
    case KeyCode::LMeta:
      return "LMeta";
    case KeyCode::RCtrl:
      return "RCtrl";
    case KeyCode::RShift:
      return "RShift";
    case KeyCode::RAlt:
      return "RAlt";
    case KeyCode::RMeta:
      return "RMeta";
    default:
      VAN_DEBUGBREAK;
      return "Unknown";
  }
}

KeyCode fromString(const std::string &arg) {
  size_t hash = hashString(arg);

  switch (hash) {
    case "A"_hash:
      return KeyCode::A;
    case "B"_hash:
      return KeyCode::B;
    case "C"_hash:
      return KeyCode::C;
    case "D"_hash:
      return KeyCode::D;
    case "E"_hash:
      return KeyCode::E;
    case "F"_hash:
      return KeyCode::F;
    case "G"_hash:
      return KeyCode::G;
    case "H"_hash:
      return KeyCode::H;
    case "I"_hash:
      return KeyCode::I;
    case "J"_hash:
      return KeyCode::J;
    case "K"_hash:
      return KeyCode::K;
    case "L"_hash:
      return KeyCode::L;
    case "M"_hash:
      return KeyCode::M;
    case "N"_hash:
      return KeyCode::N;
    case "O"_hash:
      return KeyCode::O;
    case "P"_hash:
      return KeyCode::P;
    case "Q"_hash:
      return KeyCode::Q;
    case "R"_hash:
      return KeyCode::R;
    case "S"_hash:
      return KeyCode::S;
    case "T"_hash:
      return KeyCode::T;
    case "U"_hash:
      return KeyCode::U;
    case "V"_hash:
      return KeyCode::V;
    case "W"_hash:
      return KeyCode::W;
    case "X"_hash:
      return KeyCode::X;
    case "Y"_hash:
      return KeyCode::Y;
    case "Z"_hash:
      return KeyCode::Z;
    case "Num_1"_hash:
      return KeyCode::Num_1;
    case "Num_2"_hash:
      return KeyCode::Num_2;
    case "Num_3"_hash:
      return KeyCode::Num_3;
    case "Num_4"_hash:
      return KeyCode::Num_4;
    case "Num_5"_hash:
      return KeyCode::Num_5;
    case "Num_6"_hash:
      return KeyCode::Num_6;
    case "Num_7"_hash:
      return KeyCode::Num_7;
    case "Num_8"_hash:
      return KeyCode::Num_8;
    case "Num_9"_hash:
      return KeyCode::Num_9;
    case "Num_10"_hash:
      return KeyCode::Num_10;
    case "Return"_hash:
      return KeyCode::Return;
    case "Escape"_hash:
      return KeyCode::Escape;
    case "Backspace"_hash:
      return KeyCode::Backspace;
    case "Tab"_hash:
      return KeyCode::Tab;
    case "Space"_hash:
      return KeyCode::Space;
    case "Minus"_hash:
      return KeyCode::Minus;
    case "Equals"_hash:
      return KeyCode::Equals;
    case "LeftBracket"_hash:
      return KeyCode::LeftBracket;
    case "RightBracket"_hash:
      return KeyCode::RightBracket;
    case "Backslash"_hash:
      return KeyCode::Backslash;
    case "Semicolon"_hash:
      return KeyCode::Semicolon;
    case "Apostrophe"_hash:
      return KeyCode::Apostrophe;
    case "Grave"_hash:
      return KeyCode::Grave;
    case "Comma"_hash:
      return KeyCode::Comma;
    case "Period"_hash:
      return KeyCode::Period;
    case "Slash"_hash:
      return KeyCode::Slash;
    case "Capslock"_hash:
      return KeyCode::Capslock;
    case "F1"_hash:
      return KeyCode::F1;
    case "F2"_hash:
      return KeyCode::F2;
    case "F3"_hash:
      return KeyCode::F3;
    case "F4"_hash:
      return KeyCode::F4;
    case "F5"_hash:
      return KeyCode::F5;
    case "F6"_hash:
      return KeyCode::F6;
    case "F7"_hash:
      return KeyCode::F7;
    case "F8"_hash:
      return KeyCode::F8;
    case "F9"_hash:
      return KeyCode::F9;
    case "F10"_hash:
      return KeyCode::F10;
    case "F11"_hash:
      return KeyCode::F11;
    case "F12"_hash:
      return KeyCode::F12;
    case "PrintScreen"_hash:
      return KeyCode::PrintScreen;
    case "ScrollLock"_hash:
      return KeyCode::ScrollLock;
    case "Pause"_hash:
      return KeyCode::Pause;
    case "Insert"_hash:
      return KeyCode::Insert;
    case "Home"_hash:
      return KeyCode::Home;
    case "PageUp"_hash:
      return KeyCode::PageUp;
    case "Delete"_hash:
      return KeyCode::Delete;
    case "End"_hash:
      return KeyCode::End;
    case "PageDown"_hash:
      return KeyCode::PageDown;
    case "Right"_hash:
      return KeyCode::Right;
    case "Left"_hash:
      return KeyCode::Left;
    case "Down"_hash:
      return KeyCode::Down;
    case "Up"_hash:
      return KeyCode::Up;
    case "NumLock"_hash:
      return KeyCode::NumLock;
    case "KPDivide"_hash:
      return KeyCode::KPDivide;
    case "KPMultiply"_hash:
      return KeyCode::KPMultiply;
    case "KP_Minus"_hash:
      return KeyCode::KP_Minus;
    case "KP_Plus"_hash:
      return KeyCode::KP_Plus;
    case "KP_Enter"_hash:
      return KeyCode::KP_Enter;
    case "KP_1"_hash:
      return KeyCode::KP_1;
    case "KP_2"_hash:
      return KeyCode::KP_2;
    case "KP_3"_hash:
      return KeyCode::KP_3;
    case "KP_4"_hash:
      return KeyCode::KP_4;
    case "KP_5"_hash:
      return KeyCode::KP_5;
    case "KP_6"_hash:
      return KeyCode::KP_6;
    case "KP_7"_hash:
      return KeyCode::KP_7;
    case "KP_8"_hash:
      return KeyCode::KP_8;
    case "KP_9"_hash:
      return KeyCode::KP_9;
    case "KP_0"_hash:
      return KeyCode::KP_0;
    case "KP_Period"_hash:
      return KeyCode::KP_Period;
    case "KP_Equals"_hash:
      return KeyCode::KP_Equals;
    case "F13"_hash:
      return KeyCode::F13;
    case "F14"_hash:
      return KeyCode::F14;
    case "F15"_hash:
      return KeyCode::F15;
    case "F16"_hash:
      return KeyCode::F16;
    case "F17"_hash:
      return KeyCode::F17;
    case "F18"_hash:
      return KeyCode::F18;
    case "F19"_hash:
      return KeyCode::F19;
    case "F20"_hash:
      return KeyCode::F20;
    case "F21"_hash:
      return KeyCode::F21;
    case "F22"_hash:
      return KeyCode::F22;
    case "F23"_hash:
      return KeyCode::F23;
    case "F24"_hash:
      return KeyCode::F24;
    case "Execute"_hash:
      return KeyCode::Execute;
    case "Help"_hash:
      return KeyCode::Help;
    case "Menu"_hash:
      return KeyCode::Menu;
    case "Select"_hash:
      return KeyCode::Select;
    case "Stop"_hash:
      return KeyCode::Stop;
    case "Redo"_hash:
      return KeyCode::Redo;
    case "Undo"_hash:
      return KeyCode::Undo;
    case "Cut"_hash:
      return KeyCode::Cut;
    case "Copy"_hash:
      return KeyCode::Copy;
    case "Paste"_hash:
      return KeyCode::Paste;
    case "Find"_hash:
      return KeyCode::Find;
    case "Mute"_hash:
      return KeyCode::Mute;
    case "VolumeUp"_hash:
      return KeyCode::VolumeUp;
    case "VolumeDown"_hash:
      return KeyCode::VolumeDown;
    case "KP_Comma"_hash:
      return KeyCode::KP_Comma;
    case "LCtrl"_hash:
      return KeyCode::LCtrl;
    case "LShift"_hash:
      return KeyCode::LShift;
    case "LAlt"_hash:
      return KeyCode::LAlt;
    case "LMeta"_hash:
      return KeyCode::LMeta;
    case "RCtrl"_hash:
      return KeyCode::RCtrl;
    case "RShift"_hash:
      return KeyCode::RShift;
    case "RAlt"_hash:
      return KeyCode::RAlt;
    case "RMeta"_hash:
      return KeyCode::RMeta;
    default:
      VAN_DEBUGBREAK;
      return KeyCode::Unknown;
  }
}

KeyCode fromInt(int arg) {
  switch (arg) {
    case (int)KeyCode::A:
      return KeyCode::A;
    case (int)KeyCode::B:
      return KeyCode::B;
    case (int)KeyCode::C:
      return KeyCode::C;
    case (int)KeyCode::D:
      return KeyCode::D;
    case (int)KeyCode::E:
      return KeyCode::E;
    case (int)KeyCode::F:
      return KeyCode::F;
    case (int)KeyCode::G:
      return KeyCode::G;
    case (int)KeyCode::H:
      return KeyCode::H;
    case (int)KeyCode::I:
      return KeyCode::I;
    case (int)KeyCode::J:
      return KeyCode::J;
    case (int)KeyCode::K:
      return KeyCode::K;
    case (int)KeyCode::L:
      return KeyCode::L;
    case (int)KeyCode::M:
      return KeyCode::M;
    case (int)KeyCode::N:
      return KeyCode::N;
    case (int)KeyCode::O:
      return KeyCode::O;
    case (int)KeyCode::P:
      return KeyCode::P;
    case (int)KeyCode::Q:
      return KeyCode::Q;
    case (int)KeyCode::R:
      return KeyCode::R;
    case (int)KeyCode::S:
      return KeyCode::S;
    case (int)KeyCode::T:
      return KeyCode::T;
    case (int)KeyCode::U:
      return KeyCode::U;
    case (int)KeyCode::V:
      return KeyCode::V;
    case (int)KeyCode::W:
      return KeyCode::W;
    case (int)KeyCode::X:
      return KeyCode::X;
    case (int)KeyCode::Y:
      return KeyCode::Y;
    case (int)KeyCode::Z:
      return KeyCode::Z;
    case (int)KeyCode::Num_1:
      return KeyCode::Num_1;
    case (int)KeyCode::Num_2:
      return KeyCode::Num_2;
    case (int)KeyCode::Num_3:
      return KeyCode::Num_3;
    case (int)KeyCode::Num_4:
      return KeyCode::Num_4;
    case (int)KeyCode::Num_5:
      return KeyCode::Num_5;
    case (int)KeyCode::Num_6:
      return KeyCode::Num_6;
    case (int)KeyCode::Num_7:
      return KeyCode::Num_7;
    case (int)KeyCode::Num_8:
      return KeyCode::Num_8;
    case (int)KeyCode::Num_9:
      return KeyCode::Num_9;
    case (int)KeyCode::Num_10:
      return KeyCode::Num_10;
    case (int)KeyCode::Return:
      return KeyCode::Return;
    case (int)KeyCode::Escape:
      return KeyCode::Escape;
    case (int)KeyCode::Backspace:
      return KeyCode::Backspace;
    case (int)KeyCode::Tab:
      return KeyCode::Tab;
    case (int)KeyCode::Space:
      return KeyCode::Space;
    case (int)KeyCode::Minus:
      return KeyCode::Minus;
    case (int)KeyCode::Equals:
      return KeyCode::Equals;
    case (int)KeyCode::LeftBracket:
      return KeyCode::LeftBracket;
    case (int)KeyCode::RightBracket:
      return KeyCode::RightBracket;
    case (int)KeyCode::Backslash:
      return KeyCode::Backslash;
    case (int)KeyCode::Semicolon:
      return KeyCode::Semicolon;
    case (int)KeyCode::Apostrophe:
      return KeyCode::Apostrophe;
    case (int)KeyCode::Grave:
      return KeyCode::Grave;
    case (int)KeyCode::Comma:
      return KeyCode::Comma;
    case (int)KeyCode::Period:
      return KeyCode::Period;
    case (int)KeyCode::Slash:
      return KeyCode::Slash;
    case (int)KeyCode::Capslock:
      return KeyCode::Capslock;
    case (int)KeyCode::F1:
      return KeyCode::F1;
    case (int)KeyCode::F2:
      return KeyCode::F2;
    case (int)KeyCode::F3:
      return KeyCode::F3;
    case (int)KeyCode::F4:
      return KeyCode::F4;
    case (int)KeyCode::F5:
      return KeyCode::F5;
    case (int)KeyCode::F6:
      return KeyCode::F6;
    case (int)KeyCode::F7:
      return KeyCode::F7;
    case (int)KeyCode::F8:
      return KeyCode::F8;
    case (int)KeyCode::F9:
      return KeyCode::F9;
    case (int)KeyCode::F10:
      return KeyCode::F10;
    case (int)KeyCode::F11:
      return KeyCode::F11;
    case (int)KeyCode::F12:
      return KeyCode::F12;
    case (int)KeyCode::PrintScreen:
      return KeyCode::PrintScreen;
    case (int)KeyCode::ScrollLock:
      return KeyCode::ScrollLock;
    case (int)KeyCode::Pause:
      return KeyCode::Pause;
    case (int)KeyCode::Insert:
      return KeyCode::Insert;
    case (int)KeyCode::Home:
      return KeyCode::Home;
    case (int)KeyCode::PageUp:
      return KeyCode::PageUp;
    case (int)KeyCode::Delete:
      return KeyCode::Delete;
    case (int)KeyCode::End:
      return KeyCode::End;
    case (int)KeyCode::PageDown:
      return KeyCode::PageDown;
    case (int)KeyCode::Right:
      return KeyCode::Right;
    case (int)KeyCode::Left:
      return KeyCode::Left;
    case (int)KeyCode::Down:
      return KeyCode::Down;
    case (int)KeyCode::Up:
      return KeyCode::Up;
    case (int)KeyCode::NumLock:
      return KeyCode::NumLock;
    case (int)KeyCode::KPDivide:
      return KeyCode::KPDivide;
    case (int)KeyCode::KPMultiply:
      return KeyCode::KPMultiply;
    case (int)KeyCode::KP_Minus:
      return KeyCode::KP_Minus;
    case (int)KeyCode::KP_Plus:
      return KeyCode::KP_Plus;
    case (int)KeyCode::KP_Enter:
      return KeyCode::KP_Enter;
    case (int)KeyCode::KP_1:
      return KeyCode::KP_1;
    case (int)KeyCode::KP_2:
      return KeyCode::KP_2;
    case (int)KeyCode::KP_3:
      return KeyCode::KP_3;
    case (int)KeyCode::KP_4:
      return KeyCode::KP_4;
    case (int)KeyCode::KP_5:
      return KeyCode::KP_5;
    case (int)KeyCode::KP_6:
      return KeyCode::KP_6;
    case (int)KeyCode::KP_7:
      return KeyCode::KP_7;
    case (int)KeyCode::KP_8:
      return KeyCode::KP_8;
    case (int)KeyCode::KP_9:
      return KeyCode::KP_9;
    case (int)KeyCode::KP_0:
      return KeyCode::KP_0;
    case (int)KeyCode::KP_Period:
      return KeyCode::KP_Period;
    case (int)KeyCode::KP_Equals:
      return KeyCode::KP_Equals;
    case (int)KeyCode::F13:
      return KeyCode::F13;
    case (int)KeyCode::F14:
      return KeyCode::F14;
    case (int)KeyCode::F15:
      return KeyCode::F15;
    case (int)KeyCode::F16:
      return KeyCode::F16;
    case (int)KeyCode::F17:
      return KeyCode::F17;
    case (int)KeyCode::F18:
      return KeyCode::F18;
    case (int)KeyCode::F19:
      return KeyCode::F19;
    case (int)KeyCode::F20:
      return KeyCode::F20;
    case (int)KeyCode::F21:
      return KeyCode::F21;
    case (int)KeyCode::F22:
      return KeyCode::F22;
    case (int)KeyCode::F23:
      return KeyCode::F23;
    case (int)KeyCode::F24:
      return KeyCode::F24;
    case (int)KeyCode::Execute:
      return KeyCode::Execute;
    case (int)KeyCode::Help:
      return KeyCode::Help;
    case (int)KeyCode::Menu:
      return KeyCode::Menu;
    case (int)KeyCode::Select:
      return KeyCode::Select;
    case (int)KeyCode::Stop:
      return KeyCode::Stop;
    case (int)KeyCode::Redo:
      return KeyCode::Redo;
    case (int)KeyCode::Undo:
      return KeyCode::Undo;
    case (int)KeyCode::Cut:
      return KeyCode::Cut;
    case (int)KeyCode::Copy:
      return KeyCode::Copy;
    case (int)KeyCode::Paste:
      return KeyCode::Paste;
    case (int)KeyCode::Find:
      return KeyCode::Find;
    case (int)KeyCode::Mute:
      return KeyCode::Mute;
    case (int)KeyCode::VolumeUp:
      return KeyCode::VolumeUp;
    case (int)KeyCode::VolumeDown:
      return KeyCode::VolumeDown;
    case (int)KeyCode::KP_Comma:
      return KeyCode::KP_Comma;
    case (int)KeyCode::LCtrl:
      return KeyCode::LCtrl;
    case (int)KeyCode::LShift:
      return KeyCode::LShift;
    case (int)KeyCode::LAlt:
      return KeyCode::LAlt;
    case (int)KeyCode::LMeta:
      return KeyCode::LMeta;
    case (int)KeyCode::RCtrl:
      return KeyCode::RCtrl;
    case (int)KeyCode::RShift:
      return KeyCode::RShift;
    case (int)KeyCode::RAlt:
      return KeyCode::RAlt;
    case (int)KeyCode::RMeta:
      return KeyCode::RMeta;
    default:
      VAN_DEBUGBREAK;
      return KeyCode::Unknown;
  }
}

}  // namespace vanadium::keyboard
