cmake_minimum_required(VERSION 3.7...3.20)

if (${CMAKE_VERSION} VERSION_LESS 3.12)
    cmake_policy(VERSION ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION})
endif ()

set(VENDOR_FOLDER external)

set(IMGUI_SOURCES
        ${VENDOR_FOLDER}/imgui/imgui.cpp
        ${VENDOR_FOLDER}/imgui/imgui_draw.cpp
        ${VENDOR_FOLDER}/imgui/imgui_tables.cpp
        ${VENDOR_FOLDER}/imgui/imgui_widgets.cpp
        ${VENDOR_FOLDER}/imgui/imgui_demo.cpp
        )

set(VANADIUM_SOURCES
        src/core/Application.cpp
        src/core/EventProvider.cpp
        src/core/Exceptions.cpp
        src/core/IO.cpp
        src/core/Log.cpp
        src/core/Math.cpp
        src/core/Random.cpp
        src/core/stateCommands/PopAllStatesCommand.cpp
        src/core/stateCommands/PopStateCommand.cpp
        src/core/stateCommands/PushStateCommand.cpp
        src/core/stateCommands/ReplaceStateCommand.cpp
        src/core/State.cpp
        src/core/StateStack.cpp
        src/core/Stopwatch.cpp
        src/core/Timer.cpp
        src/core/Tools.cpp
        src/core/Window.cpp
        src/graphics/BgfxCallback.cpp
        src/graphics/BgfxContext.cpp
        src/graphics/ShaderFactory.cpp
        src/platform/default/DefaultDialogs.cpp
        src/platform/default/DefaultEventProvider.cpp
        src/platform/default/DefaultIO.cpp
        src/platform/default/DefaultKeyCodes.cpp
        src/platform/default/DefaultStopwatch.cpp
        src/platform/default/DefaultTimer.cpp
        src/platform/default/DefaultWindow.cpp
        src/scene/Camera.cpp
        src/scene/FpsCamera.cpp
        src/scene/Mesh.cpp
        src/scene/PositionCamera.cpp
        src/submodules/svg/Parser.cpp
        src/submodules/svg/Rasterizer.cpp
        src/vfs/Entry.cpp
        src/vfs/FileStream.cpp
        src/vfs/Vfs.cpp
        )

set(VANADIUM_HEADERS
        src/core/Animation.h
        src/core/Application.h
        src/core/Assert.h
        src/core/Dialogs.h
        src/core/EventProvider.h
        src/core/Exceptions.h
        src/core/interfaces/Command.h
        src/core/IO.h
        src/core/KeyCodes.h
        src/core/LogFormatters.h
        src/core/Log.h
        src/core/Math.h
        src/core/Random.h
        src/core/stateCommands/PopAllStatesCommand.h
        src/core/stateCommands/PopStateCommand.h
        src/core/stateCommands/PushStateCommand.h
        src/core/stateCommands/ReplaceStateCommand.h
        src/core/State.h
        src/core/StateStack.h
        src/core/Stopwatch.h
        src/core/StringHash.h
        src/core/Timer.h
        src/core/Tools.h
        src/core/Types.h
        src/core/Version.h
        src/core/Window.h
        src/event/EventDispatcher.h
        src/event/Event.h
        src/event/KeyEvent.h
        src/event/MouseEvent.h
        src/event/WindowEvent.h
        src/graphics/BgfxCallback.h
        src/graphics/BgfxContext.h
        src/graphics/ShaderFactory.h
        src/platform/default/DefaultDialogs.h
        src/platform/default/DefaultEventProvider.h
        src/platform/default/DefaultIncludes.h
        src/platform/default/DefaultIO.h
        src/platform/default/DefaultKeyCodes.h
        src/platform/default/DefaultStopwatch.h
        src/platform/default/DefaultTimer.h
        src/platform/default/DefaultWindow.h
        src/scene/Camera.h
        src/scene/FpsCamera.h
        src/scene/Mesh.h
        src/scene/PositionCamera.h
        src/submodules/svg/Commands.h
        src/submodules/svg/Document.h
        src/submodules/svg/Layer.h
        src/submodules/svg/Parser.h
        src/submodules/svg/Path.h
        src/submodules/svg/Rasterizer.h
        src/submodules/svg/Types.h
        src/Vanadium.h
        src/vfs/Entry.h
        src/vfs/Exceptions.h
        src/vfs/FileStream.h
        src/vfs/Vfs.h
        )